# docker run -i -p 7000:5000 -p 7001:5001 --name test2 original



FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app

# copy scproj and restore as distinct layers
COPY *.sln .
COPY ./webapi/*.csproj ./webapi/
RUN dotnet restore

#copy everything else and build app
COPY webapi/. ./webapi/
WORKDIR /app/webapi
RUN dotnet publish -c Debug -o out

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS runtime
WORKDIR /app
EXPOSE 80 5000
EXPOSE 443 5001
COPY --from=build /app/webapi/out ./
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y curl unzip procps
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /publish/vsdbg;
ENTRYPOINT ["dotnet", "HelloWebApiCoreDocker.dll"]
